apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-node-app
  template:
    metadata:
      labels:
        app: my-node-app
    spec:
      containers:
      - name: my-node-app
        image: pracricetobivincent/node-js-application:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 4000
    
