apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-and-services
  namespace: default
subjects:
- kind: User
  name: tobi
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-and-services-reader
  apiGroup: rbac.authorization.k8s.io