name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE_NAME: your-dockerhub-username/your-image-name
      VERSION_FILE: .version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Increment version
      id: version
      run: |
        if [ -f "$VERSION_FILE" ]; then
          VERSION=$(cat $VERSION_FILE)
        else
          VERSION=0.0.0
        fi
        echo "Current version: $VERSION"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo $NEW_VERSION > $VERSION_FILE
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:${{ env.VERSION }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_IMAGE_NAME:${{ env.VERSION }}

    - name: Commit version change
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add $VERSION_FILE
        git commit -m "Bump version to ${{ env.VERSION }}"
        git push
