name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .
        

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure kubectl
        run: |
          kubectl config set-cluster codespace
          kubectl config set-context codespace
          kubectl config use-context codespace
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml
             kubectl apply -f service.yaml 
            