name: Build, Deploy, and Update VM

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    env:
      DOCKER_IMAGE_NAME: pracricetobivincent/node-js-application
      VERSION_FILE: .version

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Increment version
      id: version
      run: |
        if [ -f "$VERSION_FILE" ]; then
          VERSION=$(cat $VERSION_FILE)
        else
          VERSION=0.0.0
        fi
        echo "Current version: $VERSION"
        IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
        PATCH=$((PATCH + 1))
        NEW_VERSION="$MAJOR.$MINOR.$PATCH"
        echo $NEW_VERSION > $VERSION_FILE
        echo "New version: $NEW_VERSION"
        echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE_NAME:latest -t $DOCKER_IMAGE_NAME:${{ env.VERSION }} .

    - name: Push Docker image to Docker Hub
      run: |
        docker push $DOCKER_IMAGE_NAME:latest
        docker push $DOCKER_IMAGE_NAME:${{ env.VERSION }}

    - name: Commit version change
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add $VERSION_FILE
        git commit -m "Bump version to ${{ env.VERSION }}"
        git push

  update-vm:
    runs-on: ubuntu-latest

    needs: build-and-push
    
    env:
      VM_USER: your-vm-username
      VM_HOST: your-vm-ip-or-dns
      REPO_PATH: /path/to/your/repo

    steps:
    - name: SSH into Azure VM and Pull Latest Repo
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key
        chmod 600 /tmp/private_key
        ssh -o StrictHostKeyChecking=no -i /tmp/private_key $VM_USER@$VM_HOST << EOF
          cd $REPO_PATH
          git pull origin main
          # Add any additional commands if needed, e.g., restarting services
        EOF
        rm /tmp/private_key
