name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: |
          docker build -t my-app:v1 .
        

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start Minikube
        run: |
          minikube start
          minikube status
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml 
          kubectl apply -f role.yaml
          kubectl apply -f rolebinding.yaml
        - name: Get service URL
          run: |
          SERVICE_NAME=$(kubectl get svc -o jsonpath='{.items[0].metadata.name}')
          SERVICE_URL=$(kubectl get svc -o jsonpath='{.items[0].status.loadBalancer.ingress[0].hostname}')
          echo "Service URL: $SERVICE_URL"
            